#ifndef __DEVICE_CATEGORY_TYPE_H__
#define __DEVICE_CATEGORY_TYPE_H__

namespace sep
{
enum class DeviceCategoryType
{
    PROGRAMMABLE_COMMUNICATING_THERMOSTAT,
    STRIP_HEATERS,
    BASEBOARD_HEATERS,
    WATER_HEATERS,
    POOL_PUMP,
    SAUNA,
    HOT_TUB,
    SMART_APPLIANCE,
    IRRIGATION_PUMP,
    MANAGED_COMMERCIAL_INDUSTRIAL_lOADS,
    SIMPLE_MISC_LOADS,
    EXTERIOR_LIGHTING,
    INTERIOR_LIGHTING,
    LOAD_CONTROL_SWITCH,
    ENERGY_MANAGEMENT_SYSTEM,
    SMART_ENERGY_MODULE,
    ELECTRIC_VEHICLE,
    EVSE,
    VIRTUAL_MIXED_DER,
    RECIPROCATING_ENGINE,
    FUEL_CELL,
    PHOTOVOLTAIC_SYSTEM,
    COMBINED_HEAD_AND_POWER,
    COMBINED_PV_AND_STORAGE,
    OTHER_GENERATION_SYSTEM,
    OTHER_STORAGE_SYSTEM
};
}; // namespace
#endif // __DEVICE_CATEGORY_TYPE_H__